### ISSUE TITLE
Reface with a new logo and new theme

### ISSUE THREAD

**Issue by adriancole** [openzipkin/openzipkin.github.io#132]
Thanks to LINE we have a new look in zipkin (Lens). While similar, it is a new look :) Our screenshot here is from I think 2016 and will not show off things. Plus, we have a new logo in process also from LINE.

Let's try to get a new theme and screenshot with new logo images together. Some of us are meeting at LINE week of 14 July, so would be cool, if arbitrary, to do this by then.

cc @syleeeee @tacigar @huydx

**Comment by anuraaga** [comment]
Thanks to everyone, site was updated!
