### ISSUE TITLE
Getting error while downloading zipkin server

### ISSUE THREAD

**Issue by yashaswi90** [openzipkin/openzipkin.github.io#150]
Getting error while downloading zipkin server through curl -sSL https://zipkin.io/quickstart.sh | bash -sx --:- It looks like quick-start setup has failed. Please run the command again with the debug flag like below, and open an issue on https://github.com/openzipkin/openzipkin.github.io/issues/new. Make sure to include the full output of the run.

**Comment by shakuzen** [comment]
Could you include the full output of the command? For what it's worth, I just tried from my laptop and it downloaded the latest Zipkin Server successfully.

**Comment by yashaswi90** [comment]
I have tried next day and it has started working again.

Thanks.
