### ISSUE TITLE
Zipkin installatation failed on MAC Os

### ISSUE THREAD

**Issue by nitulkukadia** [openzipkin/openzipkin.github.io#173]
curl -sSL https://zipkin.io/quickstart.sh | bash -sx --

+ set -euo pipefail
+ DO_CLEANUP=0
++ tput setaf 7
++ tput bold
+ color_title=''
++ tput setaf 8
+ color_dim=''
++ tput setaf 2
+ color_good=''
++ tput setaf 1
+ color_bad=''
++ tput setaf 3
+ color_warn=''
++ tput sgr0
+ color_reset=''
+ repo=https://repo1.maven.org/maven2
+ main
+ local artifact_group=io.zipkin
+ local artifact_id=zipkin-server
+ local artifact_version=LATEST
+ local artifact_version_lowercase=latest
+ local artifact_classifier=exec
+ local artifact_group_with_slashes
+ local artifact_url
+ [[ 0 -eq 0 ]]
+ local filename=zipkin.jar
+ trap 'handle_shutdown "zipkin.jar" ' EXIT
+ [[ -n exec ]]
+ artifact_classifier_suffix=-exec
+ welcome
+ cat
Thank you for trying Zipkin!
This installer is provided as a quick-start helper, so you can try Zipkin out
without a lengthy installation process.

+ '[' io.zipkin = io.zipkin.java ']'
+ artifact_group_with_slashes=io/zipkin
++ tr '[:upper:]' '[:lower:]'
+ artifact_version_lowercase=latest
+ '[' latest = latest ']'
+ printf '%s\n' 'Fetching version number of latest io.zipkin:zipkin-server release...'
Fetching version number of latest io.zipkin:zipkin-server release...
++ fetch_latest_version io.zipkin zipkin-server
++ local artifact_group=io.zipkin
++ shift
++ local artifact_id=zipkin-server
++ shift
++ local url=https://repo1.maven.org/maven2/io/zipkin/zipkin-server/maven-metadata.xml
+++ curl -sSL https://repo1.maven.org/maven2/io/zipkin/zipkin-server/maven-metadata.xml
+++ sed -n '/<version>/s/.*<version>\([^<]*\)<\/version>.*/\1/p'
+++ tail -1
++ printf 3.0.0-rc0
+ artifact_version=3.0.0-rc0
+ verify_version_number 3.0.0-rc0
+ [[ ! 3.0.0-rc0 =~ ^[[:digit:]+\.[[:digit:]]+\.[[:digit:]]+$ ]]
+ cat
The target version is "3.0.0-rc0". That doesn't look like a valid Zipkin release version
number; this script is confused. Bailing out.

+ exit 1
+ handle_shutdown zipkin.jar
+ local status=1
+ local base_filename=zipkin.jar
+ shift
+ [[ 1 -eq 0 ]]
+ cat

**Comment by shakuzen** [comment]
@nitulkukadia it should be fixed now. Can you try again?
