### ISSUE TITLE
Switch zipkin.io to this site

### ISSUE THREAD

**Issue by abesto** [openzipkin/openzipkin.github.io#4]
Is there anything missing before doing so?

**Comment by abesto** [comment]
@adriancole I think you set up the current zipkin.io initially?

**Comment by adriancole** [comment]
yeah, but I've lost access to godaddy somewhere along the way. @rtyler I remember giving you manage products ability on godaddy.. can you add @abesto?

**Comment by abesto** [comment]
Is done. We're live.
