### ISSUE TITLE
add zipkin-go-opentracing to existing_instrumentations

### ISSUE THREAD

**Issue by adriancole** [openzipkin/openzipkin.github.io#42]
@basvanbeek I understand this is implicit via go-kit, but since not everyone uses go-kit, do you think we should call out zipkin-go-opentracing? I think it would help since you are maintaining it so well.

**Comment by basvanbeek** [comment]
Yes that'd be a good idea. Go kit implements wrappers for opentracing API. The zipkin-go-opentracing package can easily be used with or without Go kit.
