### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by chimericalidea** [openzipkin/openzipkin.github.io#5]
Instrumenting a library:

- [x] So you want to send traces to Zipkin but there is no existing library for your platform?

- [x] sr - Server Receive. The server has received the request and will start processing it. The **time between** between this and cs **is**

- [x] ss - Server Send. The server has completed processing and has sent the request back to the client. The difference between this and **ss is** the amount of time it **takes** the server to process the request.

- [x] cr Client **Receive**. The client has received the response from the server. This **defines** the end of the span. The **RPC** is considered complete when this annotation is recorded.
For instance**,** adding an annotation when a server begins and ends an expensive computation may provide insight into how much time is being spent in **pre- and post-processing** the request versus how much time is spent running the calculation.

- [x] Switch to present tense.

- [x] In order to reassemble a set of spans into a full trace**,** three pieces

- [x] if parent id is optional, does that invalidate the "three ids are required" statement?

- [x] The span id can be the same as the trace id. *Explain why you would want them to be different. 

- [x] If the service calls out to a downstream service**,** a new span 

- [x] Define IS SAMPLED and FLAGS in same way as spanId. also consistent naming ie: camel case

- [x] You start the page with, First you need... What are the next steps?
Span Receivers:

- [x] binary**-**serialized

- [x] For small architectures**,** tracers

**Comment by abesto** [comment]
FTR, we'll get around to fixing these. This is just a list so we don't forget. No action required :)

**Comment by abesto** [comment]
All checkboxes ticked, closing.
